### ISSUE TITLE
-IgnoreReboot seems to not working

### ISSUE THREAD

**Issue by ThreshTheRed** [sarog/PSWindowsUpdate#3]
Hey

We use PSUpdate with WDS and for initial setup of a computer.
After installing updates, it asks user to Reboot Computer - either to type Y or N. -AutoReboot\-IgnoreReboot is supposed to bypass that with message **After the installation process is complete, you will see the following message in the PowerShell console: ‘Reboot is required but do it manually'.**

Is there any chance to take a look at it? Thanks

**Comment by sarog** [comment]
Hi, is this when running PSWU on Windows 10?

Does the reboot occur immediately after the updates are applied or some time later (delayed)?

**Comment by ThreshTheRed** [comment]
Ah, sorry, I forgot about details.
So basically it looks like that:

`Install-WindowsUpdate -MicrosoftUpdate -AcceptAll -IgnoreReboot`

While first part of works as intended - Updates are downloaded and installed, the -IgnoreReboot doesn't.

I run it on W11. I did a similar thing, but with -AutoReboot but on W10 for testing purposes, and it worked as intedned. I assume that it's something related to W11, but not really sure what.

**Comment by sarog** [comment]
According to the [code](https://github.com/sarog/PSWindowsUpdate/blob/master/src/GetWURebootStatus.cs#L35), there's no IgnoreReboot switch. Try it with `-ManualReboot` instead. 🙂

**Comment by ThreshTheRed** [comment]
Ok, thanks, I'll check it with **Cancel reboot** as well, as it looks more promising for me - will keep you updated

**Comment by ThreshTheRed** [comment]
Tested with `-ManualReboot` and `-CancelReboot` - command don't even execute. Also, what you answered is related to CheckReboot status, rather than InstallUpdates

**Comment by sarog** [comment]
Glad to hear! I'll go ahead and close this issue.
